# 用途：提供主應用程式 PostgreSQL Cloud SQL 設定，不含密碼。
# 流程：由 00_env.sh 載入驗證，供 instance/database/user 腳本建立或比對資源。
# 重要變數：POSTGRES_DATABASE_NAME、POSTGRES_APP_USER、POSTGRES_VERSION、POSTGRES_CPU。
# 資源影響：設定會影響 Cloud SQL 規格與網路；安全/驗證限制：漂移時停止，不自動修正。
POSTGRES_IDENTIFIER_PREFIX="${PROJECT_NAME//-/_}"
POSTGRES_DATABASE_NAME="${POSTGRES_IDENTIFIER_PREFIX}"
POSTGRES_APP_USER="${POSTGRES_IDENTIFIER_PREFIX}_app"
POSTGRES_MIGRATION_USER="${POSTGRES_IDENTIFIER_PREFIX}_migration"
POSTGRES_VERSION="POSTGRES_16"

# Cloud SQL Enterprise edition 規格。
# CPU 是 vCPU 數量；memory 單位為 MB，需符合 Cloud SQL custom machine type 規則。
# 例如 2 vCPU / 7,680 MB 會對應 db-custom-2-7680。
POSTGRES_EDITION="ENTERPRISE"
POSTGRES_CPU="1"
POSTGRES_MEMORY_MB="3840"

# 磁碟容量，單位為 GB；正式環境至少建議 20 GB。
POSTGRES_STORAGE_GB="20"

POSTGRES_NETWORK_NAME="${PROJECT_NAME}-vpc"
POSTGRES_INSTANCE_NAME="${PROJECT_NAME}-main-app-postgres"

MYSQL_VERSION="MYSQL_8_0"
MYSQL_EDITION="ENTERPRISE"
MYSQL_CPU="1"
MYSQL_MEMORY_MB="3840"
MYSQL_STORAGE_GB="20"
MYSQL_NETWORK_NAME="${PROJECT_NAME}-vpc"
MYSQL_INSTANCE_NAME="${PROJECT_NAME}-cosigner-mysql"
