#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
GLOBAL_ENV_FILE="${GLOBAL_ENV_FILE:-${SCRIPT_DIR}/../../global-env/env.sh}"
MODULE_ENV_FILE="${MODULE_ENV_FILE:-${SCRIPT_DIR}/env/env.sh}"

for env_file in "$GLOBAL_ENV_FILE" "$MODULE_ENV_FILE"; do
  [[ -f "$env_file" ]] || { printf 'Environment file not found: %s\n' "$env_file" >&2; exit 1; }
done
source "$GLOBAL_ENV_FILE"
source "$MODULE_ENV_FILE"

for variable in PROJECT_NAME GOOGLE_PROJECT_ID GOOGLE_PROJECT_REGION EXEC_IAM_ACCOUNT \
  ROLE_ID ROLE_TITLE ROLE_DESCRIPTION KMS_KEYRING MYSQL_VERSION MYSQL_EDITION \
  MYSQL_CPU MYSQL_MEMORY_MB MYSQL_STORAGE_GB MYSQL_NETWORK_NAME MYSQL_INSTANCE_NAME \
  VM_ZONE VM_MACHINE_TYPE VM_VPC_NETWORK; do
  [[ -n "${!variable:-}" ]] || { printf '%s is not configured\n' "$variable" >&2; exit 1; }
done

export PROJECT_NAME GOOGLE_PROJECT_ID GOOGLE_PROJECT_REGION EXEC_IAM_ACCOUNT
export ROLE_ID ROLE_TITLE ROLE_DESCRIPTION KMS_KEYRING MYSQL_VERSION MYSQL_EDITION
export MYSQL_CPU MYSQL_MEMORY_MB MYSQL_STORAGE_GB MYSQL_NETWORK_NAME MYSQL_INSTANCE_NAME
export VM_ZONE VM_MACHINE_TYPE VM_VPC_NETWORK
