#!/usr/bin/env bash
# 用途：載入 Cloud SQL 模組與全域環境，驗證 PostgreSQL instance/database/user 設定。
# 流程：讀取 env、保留全域專案值並匯出 Cloud SQL 資源名稱。
# 重要變數：POSTGRES_DATABASE_NAME、POSTGRES_APP_USER、POSTGRES_VERSION、POSTGRES_CPU、POSTGRES_STORAGE_GB。
# 資源影響：只載入與驗證設定；缺少欄位會在建立 Cloud SQL 前停止。
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
GLOBAL_ENV_FILE="${GLOBAL_ENV_FILE:-${SCRIPT_DIR}/../../global-env/env.sh}"
MODULE_ENV_FILE="${MODULE_ENV_FILE:-${SCRIPT_DIR}/env/env.sh}"

for env_file in "$GLOBAL_ENV_FILE" "$MODULE_ENV_FILE"; do
  if [[ ! -f "$env_file" ]]; then
    printf 'Environment file not found: %s\n' "$env_file" >&2
    return 1 2>/dev/null || exit 1
  fi
done
source "$GLOBAL_ENV_FILE"
GLOBAL_PROJECT_NAME="$PROJECT_NAME"
GLOBAL_GOOGLE_PROJECT_ID="$GOOGLE_PROJECT_ID"
GLOBAL_GOOGLE_PROJECT_REGION="$GOOGLE_PROJECT_REGION"
GLOBAL_EXEC_IAM_ACCOUNT="$EXEC_IAM_ACCOUNT"
source "$MODULE_ENV_FILE"
PROJECT_NAME="$GLOBAL_PROJECT_NAME"
GOOGLE_PROJECT_ID="$GLOBAL_GOOGLE_PROJECT_ID"
GOOGLE_PROJECT_REGION="$GLOBAL_GOOGLE_PROJECT_REGION"
EXEC_IAM_ACCOUNT="$GLOBAL_EXEC_IAM_ACCOUNT"

for variable in PROJECT_NAME GOOGLE_PROJECT_ID GOOGLE_PROJECT_REGION EXEC_IAM_ACCOUNT \
  POSTGRES_DATABASE_NAME POSTGRES_APP_USER POSTGRES_MIGRATION_USER POSTGRES_VERSION \
  POSTGRES_EDITION POSTGRES_CPU POSTGRES_MEMORY_MB POSTGRES_STORAGE_GB; do
  if [[ -z "${!variable:-}" ]]; then
    printf '%s is not configured\n' "$variable" >&2
    return 1 2>/dev/null || exit 1
  fi
done

export PROJECT_NAME GOOGLE_PROJECT_ID GOOGLE_PROJECT_REGION EXEC_IAM_ACCOUNT
export POSTGRES_DATABASE_NAME POSTGRES_APP_USER POSTGRES_MIGRATION_USER
export POSTGRES_VERSION POSTGRES_EDITION POSTGRES_CPU POSTGRES_MEMORY_MB POSTGRES_STORAGE_GB \
  POSTGRES_NETWORK_NAME POSTGRES_INSTANCE_NAME
