#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
GLOBAL_ENV_FILE="${GLOBAL_ENV_FILE:-${SCRIPT_DIR}/../../global-env/env.sh}"
MODULE_ENV_FILE="${MODULE_ENV_FILE:-${SCRIPT_DIR}/env/env.sh}"
source "${GLOBAL_ENV_FILE}"
source "${MODULE_ENV_FILE}"

for variable in PROJECT_NAME GOOGLE_PROJECT_ID GOOGLE_PROJECT_REGION MYSQL_VERSION MYSQL_EDITION \
  MYSQL_CPU MYSQL_MEMORY_MB MYSQL_STORAGE_GB MYSQL_NETWORK_NAME MYSQL_INSTANCE_NAME; do
  [[ -n "${!variable:-}" ]] || { printf '%s is not configured\n' "${variable}" >&2; exit 1; }
done
export PROJECT_NAME GOOGLE_PROJECT_ID GOOGLE_PROJECT_REGION MYSQL_VERSION MYSQL_EDITION
export MYSQL_CPU MYSQL_MEMORY_MB MYSQL_STORAGE_GB MYSQL_NETWORK_NAME MYSQL_INSTANCE_NAME
