#!/usr/bin/env bash
# 用途：載入全域環境與主應用程式唯一模組 env。
# 資源影響：只載入與驗證設定；密碼與 secret value 不由本檔處理。
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
GLOBAL_ENV_FILE="${GLOBAL_ENV_FILE:-${SCRIPT_DIR}/../../global-env/env.sh}"
MODULE_ENV_FILE="${MODULE_ENV_FILE:-${SCRIPT_DIR}/env/env.sh}"

for env_file in "$GLOBAL_ENV_FILE" "$MODULE_ENV_FILE"; do
  if [[ ! -f "$env_file" ]]; then
    printf 'Environment file not found: %s\n' "$env_file" >&2
    return 1 2>/dev/null || exit 1
  fi
done
source "$GLOBAL_ENV_FILE"
GLOBAL_PROJECT_NAME="$PROJECT_NAME"
GLOBAL_GOOGLE_PROJECT_ID="$GOOGLE_PROJECT_ID"
GLOBAL_GOOGLE_PROJECT_REGION="$GOOGLE_PROJECT_REGION"
GLOBAL_EXEC_IAM_ACCOUNT="$EXEC_IAM_ACCOUNT"
source "$MODULE_ENV_FILE"
source "${SCRIPT_DIR}/secrets.env.sh"
PROJECT_NAME="$GLOBAL_PROJECT_NAME"
GOOGLE_PROJECT_ID="$GLOBAL_GOOGLE_PROJECT_ID"
GOOGLE_PROJECT_REGION="$GLOBAL_GOOGLE_PROJECT_REGION"
EXEC_IAM_ACCOUNT="$GLOBAL_EXEC_IAM_ACCOUNT"

for variable in PROJECT_NAME GOOGLE_PROJECT_ID GOOGLE_PROJECT_REGION EXEC_IAM_ACCOUNT \
  POSTGRES_DATABASE_NAME POSTGRES_APP_USER POSTGRES_MIGRATION_USER POSTGRES_VERSION \
  POSTGRES_EDITION POSTGRES_CPU POSTGRES_MEMORY_MB POSTGRES_STORAGE_GB; do
  if [[ -z "${!variable:-}" ]]; then
    printf '%s is not configured\n' "$variable" >&2
    return 1 2>/dev/null || exit 1
  fi
done

export PROJECT_NAME GOOGLE_PROJECT_ID GOOGLE_PROJECT_REGION EXEC_IAM_ACCOUNT
export POSTGRES_DATABASE_NAME POSTGRES_APP_USER POSTGRES_MIGRATION_USER
export POSTGRES_VERSION POSTGRES_EDITION POSTGRES_CPU POSTGRES_MEMORY_MB POSTGRES_STORAGE_GB \
  POSTGRES_NETWORK_NAME POSTGRES_INSTANCE_NAME
export CLOUD_BUILD_CONNECTION_NAME CLOUD_BUILD_REPOSITORY_NAME
export APP_SECRET_MAPPING MIGRATION_SECRET_MAPPING APP_SERVICE_ACCOUNT_NAME \
  MIGRATION_SERVICE_ACCOUNT_NAME DEPLOY_SERVICE_ACCOUNT_NAME APP_RUNTIME_ENV_VARS \
  MIGRATION_RUNTIME_ENV_VARS APP_VPC_ARGS MIGRATION_VPC_ARGS CLOUD_BUILD_SOURCE_BRANCH \
  APP_MIN_INSTANCE APP_MAX_INSTANCE APP_CPU APP_MEMORY APP_TIMEOUT APP_CONCURRENCY \
  PRODUCTION_TRIGGER_NAME PRODUCTION_APP_NAME PRODUCTION_MIGRATION_JOB_NAME \
  NETWORK_NAME MAIN_APP_SUBNET_NAME MAIN_APP_SUBNET_CIDR ROUTER_NAME EGRESS_IP_NAME NAT_NAME
